Native android module functionality
true-hamid/rn-android-sms-retriever pull request #1
Opened 2023-08-15 08:21 UTC by mustfaibra

Added reading OTP code native functionality.
Added reading full SMS native functionality.

2023-08-15 19:03 UTC, true-hamid requested changes

2023-08-18 12:16 UTC, mustfaibra commented on android/gradle/wrapper/gradle-wrapper.properties
Yeah of course, they are necessary.

2023-08-18 12:20 UTC, mustfaibra commented on android/src/main/java/com/rnandroidsmsretriever/RnAndroidSmsRetrieverModule.kt
> +              Log.d(
We can do handle this by checking the BuildConfig.Debug flag before printing it.

2023-08-18 12:27 UTC, mustfaibra commented on android/src/main/java/com/rnandroidsmsretriever/RnAndroidSmsRetrieverModule.kt
> +    }
No, the else clause is not required here because the logic inside the if block is only required if the Android version is 8.0 and higher.

2023-08-18 12:28 UTC, mustfaibra commented on example/ios/RnAndroidSmsRetrieverExample.xcodeproj/project.pbxproj
Yeah, you can go ahead and delete everything related to iOS.

2023-08-18 12:37 UTC, mustfaibra commented on android/src/oldarch/RnAndroidSmsRetrieverSpec.kt
> -  abstract fun multiply(a: Double, b: Double, promise: Promise)
Yeah, indeed.

2023-08-18 12:38 UTC, mustfaibra commented on android/src/main/java/com/rnandroidsmsretriever/utils/SmsRequest.kt
> +  override val otpLength: Int,
No we do, as we need it to create a matcher for the incoming message.

2023-08-18 12:39 UTC, mustfaibra commented on android/src/main/java/com/rnandroidsmsretriever/RnAndroidSmsRetrieverModule.kt
> +  fun getSms(otpLength: Int, promise: Promise) {
No we do, as we need it to create a matcher for the incoming message.

2023-08-28 02:45 UTC, closed without merging